// Installer for the custom connector.
//
//   node install.mjs            -> NON-DESTRUCTIVE: register the MCP server with Claude Code
//                                  (`claude mcp add`) + write OUR own native-host manifest +
//                                  wrapper. Does NOT touch Anthropic's manifests, so on its
//                                  own it does not yet route the extension to us.
//   node install.mjs --activate -> ALSO repoint the live com.anthropic.* manifests (Desktop
//                                  FIRST, then Claude Code) to our host, backing each up to
//                                  a .bak first. This is what makes the patched extension
//                                  reach us — and it disables the official connector(s) while
//                                  active (Desktop's browser feature included). Revert by
//                                  restoring the .bak files. Run this only when you're present.
//   node install.mjs --dry-run  -> print every action without doing anything.
//
// The pure planning functions below are exported so the dry-run path is fully unit-tested
// without mutating Claude Code config or Chrome's manifests.

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const BRIDGE = path.join(HERE, "bridge.mjs");
const WRAPPER = path.join(HERE, "chrome-native-host"); // generated; machine-specific (gitignored)

export const SERVER_NAME = "claude-in-chrome";
export const OUR_HOST_NAME = "com.claude_custom.browser_connector";
export const OFFICIAL_EXT_ID = "fcoeoabgfenejglbffodgkkbkcdhcgfn";
export const ANTHROPIC_HOST_NAMES = [
  "com.anthropic.claude_browser_extension",      // Desktop — the extension tries this FIRST
  "com.anthropic.claude_code_browser_extension", // Claude Code
];

export function mcpAddArgv(bridgePath = BRIDGE, nodePath = process.execPath) {
  return ["mcp", "add", SERVER_NAME, "--", nodePath, bridgePath, "--mcp"];
}

export function wrapperScript(nodePath, bridgePath = BRIDGE) {
  return `#!/bin/sh\n# Custom Claude-in-Chrome connector native host. Generated by install.mjs — do not edit.\nexec "${nodePath}" "${bridgePath}" --native-host\n`;
}

export function ourManifest(wrapperPath) {
  return {
    name: OUR_HOST_NAME,
    description: "Custom Claude-in-Chrome connector (subscription-free) native host",
    path: wrapperPath,
    type: "stdio",
    allowed_origins: [`chrome-extension://${OFFICIAL_EXT_ID}/`],
  };
}

// macOS Chrome native-messaging hosts dir. (Other browsers/OSes are a follow-up.)
export function nativeMessagingDir() {
  return path.join(os.homedir(), "Library", "Application Support", "Google", "Chrome", "NativeMessagingHosts");
}

// Pure: compute what `--activate` WOULD do to the live com.anthropic.* manifests — back each
// up and repoint its `path` to our wrapper, preserving the rest (incl. allowed_origins).
// Reads existing manifests; writes nothing.
export function planActivation(dir, wrapperPath) {
  const actions = [];
  for (const name of ANTHROPIC_HOST_NAMES) {
    const manifestPath = path.join(dir, `${name}.json`);
    if (!fs.existsSync(manifestPath)) continue;
    const original = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
    actions.push({ name, manifestPath, bakPath: `${manifestPath}.bak`, repointed: { ...original, path: wrapperPath } });
  }
  return actions;
}

// --- executors (only run when invoked directly; these mutate the environment) ---

function installDefault(log = console.log) {
  const dir = nativeMessagingDir();
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(WRAPPER, wrapperScript(process.execPath), { mode: 0o755 });
  fs.chmodSync(WRAPPER, 0o755);
  const manifestPath = path.join(dir, `${OUR_HOST_NAME}.json`);
  fs.writeFileSync(manifestPath, JSON.stringify(ourManifest(WRAPPER), null, 2));
  log(`wrote wrapper  ${WRAPPER}`);
  log(`wrote manifest ${manifestPath}  (non-destructive — official manifests untouched)`);
  execFileSync("claude", mcpAddArgv(), { stdio: "inherit" });
  log(`registered MCP server "${SERVER_NAME}" with Claude Code`);
}

function activate(log = console.log) {
  const actions = planActivation(nativeMessagingDir(), WRAPPER);
  if (actions.length === 0) { log("no com.anthropic.* manifests found — nothing to activate against"); return; }
  for (const a of actions) {
    if (!fs.existsSync(a.bakPath)) fs.copyFileSync(a.manifestPath, a.bakPath);
    fs.writeFileSync(a.manifestPath, JSON.stringify(a.repointed, null, 2));
    log(`repointed ${a.name} -> our host (backup: ${path.basename(a.bakPath)})`);
  }
  log("ACTIVE: the patched extension will now reach our connector. Restore the .bak files to revert.");
}

function printDryRun(log = console.log) {
  log("$ claude " + mcpAddArgv().join(" "));
  log("\nour native-host manifest:\n" + JSON.stringify(ourManifest(WRAPPER), null, 2));
  log("\nwrapper script:\n" + wrapperScript(process.execPath));
  const plan = planActivation(nativeMessagingDir(), WRAPPER);
  log(`--activate would back up + repoint ${plan.length} com.anthropic.* manifest(s): ${plan.map((a) => a.name).join(", ") || "(none found)"}`);
}

const isMain = import.meta.url === pathToFileURL(process.argv[1] || "").href;
if (isMain) {
  const args = new Set(process.argv.slice(2));
  if (args.has("--dry-run")) printDryRun();
  else {
    installDefault();
    if (args.has("--activate")) activate();
    else console.log("\nNon-destructive install done. Run `node install.mjs --activate` (when present) to route the extension to this connector.");
  }
}
